version: '3'

services:

    # Nginx Service
    nginx:
        image: 'nginx:1.18'
        ports:
            - '80:80'
        volumes:
            - '.:/app'
            - './docker/nginx:/etc/nginx/conf.d'
        depends_on:
            - web
        restart: always
        healthcheck:
            test: '/bin/bash service nginx status || exit 1'
            interval: 3s
            timeout: 1s
            retries: 5

    # MYSQL Service (DB)
    db:
        image: 'mysql:5.7'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=silverback
            - MYSQL_USER=silverback
            - MYSQL_PASSWORD=secret
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        restart: always
        healthcheck:
            test: '/usr/bin/mysql --user=silverback --password=secret --execute "SHOW DATABASES;"'
            interval: 3s
            timeout: 1s
            retries: 5

    # Web UI Service
    web:
        image: "clivern/silverback:latest"
        build: .
        command: 'gunicorn --bind 0.0.0.0:8000 app.wsgi'
        volumes:
            - '.:/app'
        depends_on:
            - db
            - redis
            - rabbitmq
        restart: always
        healthcheck:
            test: 'python3 manage.py health check'
            interval: 3s
            timeout: 1s
            retries: 5

    # Worker1 Service
    worker1:
        image: "clivern/silverback:latest"
        build: .
        command: 'celery -A app worker --loglevel=info -n worker1'
        volumes:
            - '.:/app'
        depends_on:
            - db
            - redis
            - rabbitmq
        restart: always
        healthcheck:
            test: 'python manage.py health check'
            interval: 3s
            timeout: 1s
            retries: 5

    # Worker2 Service
    worker2:
        image: "clivern/silverback:latest"
        build: .
        command: 'celery -A app worker --loglevel=info -n worker2'
        volumes:
            - '.:/app'
        depends_on:
            - db
            - redis
            - rabbitmq
        restart: always
        healthcheck:
            test: 'python manage.py health check'
            interval: 3s
            timeout: 1s
            retries: 5

    # Redis Service
    redis:
        image: 'redis:3.2-alpine'
        volumes:
            - 'redis_data:/data'
        restart: always

    # RabbitMQ Service
    rabbitmq:
        image: 'rabbitmq:3-management'
        hostname: rabbit
        ports:
            - '15672:15672'
        labels:
            NAME: rabbitmq
        volumes:
            - './docker/rabbitmq/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config'
        restart: always

volumes:
    redis_data: null
